version: '3'
services:
  app:
    container_name: app
    build: app
    links:
      - db
  nginx:
    container_name: ngin
    build: nginx
    ports:
      - "8080:80"
    links:
      - app
  db:
    image: "mysql:5.7"
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=userpwd
